version: "3"
services:
  go:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on: 
      - db
    networks:
      - default
  db:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql/:rw
      - ./users.sql:/docker-entrypoint-initdb.d/users.sql
    restart: always
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: "11b37616bd2a"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test1234"
      MYSQL_DATABASE: "users"
      
networks:
  default:
    driver: bridge
